blank_issues_enabled: false
contact_links:
  - name: ğŸ› Report a Bug
    url: https://github.com/yokwejuste/local-django/issues/new?template=bug_report.md
    about: Report a bug to help improve the project.
  - name: ğŸš€ Request a Feature
    url: https://github.com/yokwejuste/local-django/issues/new?template=feature_request.md
    about: Suggest a new feature or improvement.
